project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('todo/', include('todo.urls')),
    path('videos/', include('videos.urls')),
    path('coupon/', include('coupon.urls')),
    path('', include('myprofile.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.review_list, name='review_list'),
    path('detail/<int:pk>/', views.review_detail, name='review_detail'),
    path('create/', views.review_create, name='review_create'),
    path('update/<int:pk>/', views.review_update, name='review_update'),
    path('delete/<int:pk>/', views.review_delete, name='review_delete'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('create/', views.todo_create, name='todo_create'),
    path('detail/<int:todo_id>', views.todo_detail, name='todo_detail'),
    path('update/<int:todo_id>', views.todo_update, name='todo_update'),
    path('delete/<int:todo_id>', views.todo_delete, name='todo_delete'),
]

reviews/models.py
from django.db import models
from django.utils import timezone

class Review(models.Model):
    STARS = (
        (1, '☆'),
        (2, '☆☆'),
        (3, '☆☆☆'),
        (4, '☆☆☆☆'),
        (5, '☆☆☆☆☆'),
    )
    store_name = models.CharField('店名', max_length=255)
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('口コミテキスト', blank=True)
    stars = models.IntegerField('星の数', choices=STARS)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

reviews/forms.py
from django import forms
from .models import Review

class ReviewCreateForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = '__all__'

reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Review
from .forms import ReviewCreateForm

def review_list(request):
    context = {
        'review_list': Review.objects.all(),
    }
    return render(request, 'reviews/review_list.html', context)

def review_detail(request, pk):
    context = {
        'review': Review.objects.get(pk=pk),
    }
    return render(request, 'reviews/review_detail.html', context)

def review_create(request):
    if request.method == 'GET':
        context = {
        'form': ReviewCreateForm()
        }
        return render(request, 'reviews/review_form.html', context)
    else:
        form = ReviewCreateForm(request.POST)
        form.save()
        return redirect('reviews:review_list')

def review_update(request, pk):
    review = Review.objects.get(pk=pk)
    form = ReviewCreateForm(request.POST or None, instance=review)
    if request.method == 'POST':
        form.save()
        return redirect('reviews:review_list')
    
    context = {
        'form': form
    }
    return render(request, 'reviews/review_form.html', context)

def review_delete(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        'review': review
    }
    if request.method == 'POST':
        review.delete()
        return redirect('reviews:review_list')
    return render(request, 'reviews/review_confirm_delete.html', context)

reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>タイトル</title>
</head>
<body>
    <header>Reviews</header>
    {% block content %}{% endblock %}
</body>
</html>

reviews/templates/reviews/review_confirm_delete.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>削除</h1>
    <p>{{ review.store_name }}-{{ review.title }} を削除します。よろしいですか。</p>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>口コミ一覧</h1>
        <h2>{{ review.store_name }}</h2>
        <p>{{ review.get_stars_display }}-{{ review.text }}</p>
        <a href="{% url 'reviews:review_update' review.pk %}">更新</a>
        <a href="{% url 'reviews:review_delete' review.pk %}">削除</a>
{% endblock %}

reviews/templates/reviews/review_form.html
{% extends 'reviews/base.html' %}

{% block content %}
    <p>作成ページ</p>
    <form action="" method="POST">  <!--review_list_send-->
        {{ form.as_p }}
        {% csrf_token %}
    <button type="submit">送信</button>
    </form>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>口コミ一覧</h1>
    {% for review in review_list %}
        <h2><a href="{% url 'reviews:review_detail' review.pk %}">{{ review.store_name }}</a></h2>
        <p>{{ review.get_stars_display }}-{{ review.text }}</p>
    {% endfor %}
    <a href="{% url 'reviews:review_create' %}">口コミ作成ページへ</a>
{% endblock %}