myprofile/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myprofile'

urlpatterns = [
    path('resume/', views.resume, name='resume'),
    path('', views.top, name='top'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('todo/', include('todo.urls')),
    path('videos/', include('videos.urls')),
    path('coupon/', include('coupon.urls')),
    path('', include('myprofile.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('create/', views.todo_create, name='todo_create'),
    path('detail/<int:todo_id>', views.todo_detail, name='todo_detail'),
    path('update/<int:todo_id>', views.todo_update, name='todo_update'),
    path('delete/<int:todo_id>', views.todo_delete, name='todo_delete'),
]

myprofile/models.py
from django.db import models

# Create your models here.

myprofile/views.py
from django.shortcuts import render

def top(request):
    context = {
        'name': 'たろう',
    }
    return render(request, 'myprofile/top.html', context)

def resume(request):
    return render(request, 'myprofile/resume.html')

myprofile/templates/myprofile/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>Taro's Profile</header>
    <a href="{% url 'myprofile:top' %}">1ページ目へ</a>
    <a href="{% url 'myprofile:resume' %}">2ページ目へ</a>
    {% block content %}{% endblock %}
</body>
</html>

myprofile/templates/myprofile/resume.html
{% extends 'myprofile/base.html' %}

{% block title %}トップページ{% endblock %}

{% block content %}<p>2ページ目</p>{% endblock %}

myprofile/templates/myprofile/top.html
{% extends 'myprofile/base.html' %}

{% block title %}トップページ{% endblock %}

{% block content %}<p>1ページ目{{name}}</p>{% endblock %}