project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('todo/', include('todo.urls')),
    path('videos/', include('videos.urls')),
    path('coupon/', include('coupon.urls')),
    path('', include('myprofile.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('create/', views.todo_create, name='todo_create'),
    path('detail/<int:todo_id>', views.todo_detail, name='todo_detail'),
    path('update/<int:todo_id>', views.todo_update, name='todo_update'),
    path('delete/<int:todo_id>', views.todo_delete, name='todo_delete'),
]

todo/models.py
from django.db import models

class TodoList(models.Model):
    STATE = (
        (1,'未実行'),
        (2,'実行中'),
        (3,'終了')
    )
    name = models.CharField('内容', max_length=255)
    state = models.IntegerField('状態', choices=STATE)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from .models import TodoList

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = '__all__'

todo/views.py
from django.shortcuts import render, redirect
from .models import TodoList
from .forms import TodoListForm

def todo_list(request):
    context = {
        'todo_list': TodoList.objects.all(),
    }
    return render(request, 'todo/todo_list.html', context)

def todo_create(request):
    if request.method == 'GET':
        context = {
            'form': TodoListForm(),
        }
        return render(request, 'todo/todo_form.html', context)
    else:
        form = TodoListForm(request.POST)
        form.save()
        return redirect('todo:todo_list')

def todo_detail(request, todo_id):
    context = {
        'todo': TodoList.objects.get(id=todo_id),
    }
    return render(request, 'todo/todo_detail.html', context)

def todo_update(request, todo_id):
    if request.method == 'GET':
        todo = TodoList.objects.get(id=todo_id)
        form = TodoListForm(instance=todo)
        context = {
            'form': form,
        }
        return render(request, 'todo/todo_form.html', context)
    else:
        todo = TodoList.objects.get(id=todo_id)
        form = TodoListForm(request.POST, instance=todo)  #instance
        form.save()
        return redirect('todo:todo_list')

def todo_delete(request, todo_id):
    if request.method == 'GET':
        context = {
            'todo': TodoList.objects.get(id=todo_id),
        }
        return render(request, 'todo/todo_confirm_delete.html', context)
    else:
        todo = TodoList.objects.get(id=todo_id)
        todo.delete()
        return redirect('todo:todo_list')

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>Todo list</header>
    {% block content %}{% endblock %}
</body>
</html>

todo/templates/todo/todo_confirm_delete.html
{% extends 'todo/base.html' %}

{% block title %}トップページ{% endblock %}

{% block content %}
    <h2>削除確認</h2>
    <p>「{{ todo.name }}」を削除しますか。</p>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

todo/templates/todo/todo_detail.html
{% extends 'todo/base.html' %}

{% block title %}トップページ{% endblock %}

{% block content %}
    <p>内容：{{ todo.name }}、 状態：{{ todo.get_state_display }}</p>
    <a href="{% url 'todo:todo_update' todo.id %}">編集</a>
    <a href="{% url 'todo:todo_delete' todo.id %}">削除</a>
{% endblock %}

todo/templates/todo/todo_form.html
{% extends 'todo/base.html' %}

{% block title %}追加ページ{% endblock %}

{% block content %}
    {% if form.instance.id %}
        <h2>編集</h2>
    {% else %}
        <h2>追加フォーム</h2>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">送信</button>
    </form>
{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'todo/base.html' %}

{% block title %}トップページ{% endblock %}

{% block content %}
    {% for todo in todo_list %}
        <p>内容：<a href="{% url 'todo:todo_detail' todo.id %}">{{ todo.name }}</a>、 状態：{{ todo.get_state_display }}</p>
    {% endfor %}
    <a href="{% url 'todo:todo_create' %}">追加</a>
{% endblock %}