project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('todo/', include('todo.urls')),
    path('videos/', include('videos.urls')),
    path('coupon/', include('coupon.urls')),
    path('', include('myprofile.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('create/', views.todo_create, name='todo_create'),
    path('detail/<int:todo_id>', views.todo_detail, name='todo_detail'),
    path('update/<int:todo_id>', views.todo_update, name='todo_update'),
    path('delete/<int:todo_id>', views.todo_delete, name='todo_delete'),
]

videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

videos/models.py
from django.db import models

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

videos/forms.py
from django import forms
#from .models import Video

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

videos/views.py
from django.shortcuts import render, redirect
from .models import Photo
from .forms import PhotoForm

def index(request):
    context = {
        'form': PhotoForm(),
    }
    return render(request, 'videos/index.html', context)

def predict(request):
    form = PhotoForm(request.POST, request.FILES)
    
    form.is_valid()  # 無効の場合

    photo = Photo(image=form.cleaned_data['image'])
    
    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
    }
    
    return render(request, 'videos/result.html', context)

videos/templates/videos/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>動画アップロード</title>
</head>
<body>
    <header>Videos</header>
    {% block content %}{% endblock %}
</body>
</html>

videos/templates/videos/index.html
{% extends 'videos/base.html' %}

{% block content %}
<div>
    <h4>車・バイク推定アプリ</h4>
    <p>画像ファイルを選択して推定ボタンをクリックしてください。</p>
    <form action="{% url 'videos:predict' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.image }}
        <label>
            推定したいファイルを選択してください。
        </label>
        <button type="submit">推定する!</button>
    </form>
</div>
{% endblock %}

videos/templates/videos/result.html
{% extends 'videos/base.html' %}

{% block content %}
    <h4>車・バイク推定結果</h4>
        <p>{{ photo_name }}</p>
    <p><a href="{% url 'videos:index' %}">画像選択メニューに戻る</a></p>
{% endblock %}